---
title: "My Portfolio"
author: "Chris"
date: "2024-02-21"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

### Introduction

Welcome to my portfolio!

### Visualizations

This page will show my beautiful plots.

```{r}
remotes::install_github('jaburgoyne/compmus')

library(tidyverse)
library(spotifyr)
library(compmus)

wood <-
  get_tidy_audio_analysis("4Au7Ih5wFRc0LZ9sMoT9Z3") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)


wood |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```


***
This is my sidebar.

### Conclusion

```{r}
chapelle <-
  get_tidy_audio_analysis("0bCTqxYSyYP7OawV9cam1V") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

compmus_long_distance(
  wood |> mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  chapelle |> mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  feature = pitches,
  method = "euclidean"
) |>
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "The Tallis Scholars", y = "La Chapelle Royale") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)
```


This page will list my conlcusions.